{% set name = "napari-annotate" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-annotate-{{ version }}.tar.gz
  sha256: 42b4431fca2b3b43335e6fb63b281b962de2b3b8361202ee81bbd9aee2e8b317

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - scikit-image
    - tifffile

test:
  imports:
    - napari_annotate
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/WyssCenter
  summary: Annotate large 2D slides
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
